# Generated by Django 5.2 on 2025-04-18 08:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_code", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("year", models.IntegerField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-year", "project_code"],
            },
        ),
        migrations.CreateModel(
            name="ProjectFolder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "folder_type",
                    models.CharField(
                        choices=[
                            ("BUSINESS", "Business"),
                            ("TECHNICAL", "Technical"),
                            ("ADMIN", "Administrative"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("relative_path", models.CharField(max_length=1000)),
                (
                    "parent_folder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subfolders",
                        to="files.projectfolder",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="folders",
                        to="files.project",
                    ),
                ),
            ],
            options={
                "unique_together": {("project", "relative_path")},
            },
        ),
        migrations.CreateModel(
            name="ProjectAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("analysis_type", models.CharField(max_length=50)),
                (
                    "analysis_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("results_json", models.JSONField()),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyses",
                        to="files.project",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["project", "analysis_type"],
                        name="files_proje_project_704364_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FileMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("file_type", models.CharField(max_length=50)),
                ("full_path", models.CharField(max_length=1000)),
                ("size_bytes", models.BigIntegerField()),
                ("created_time", models.DateTimeField()),
                ("modified_time", models.DateTimeField()),
                ("mime_type", models.CharField(blank=True, max_length=100, null=True)),
                ("md5_hash", models.CharField(blank=True, max_length=32, null=True)),
                ("sha1_hash", models.CharField(blank=True, max_length=40, null=True)),
                ("sha256_hash", models.CharField(blank=True, max_length=64, null=True)),
                ("extracted_text", models.TextField(blank=True, null=True)),
                ("metadata_json", models.JSONField(default=dict)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="files.project",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="files.projectfolder",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["project", "folder"],
                        name="files_filem_project_b41dfc_idx",
                    ),
                    models.Index(
                        fields=["file_type"], name="files_filem_file_ty_5849ff_idx"
                    ),
                ],
            },
        ),
    ]
