# Generated by Django 5.2 on 2025-04-21 09:01

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone

def create_default_project(apps, schema_editor):
    Project = apps.get_model('projects', 'Project')
    Client = apps.get_model('clients', 'Client')
    if not Project.objects.filter(id=1).exists():
        # Get or create a default client
        client, _ = Client.objects.get_or_create(
            name="Default Client",
            defaults={
                'email': 'default@example.com',
                'phone': '000-000-0000'
            }
        )
        now = timezone.now()
        Project.objects.create(
            id=1,
            title="Default Project",
            description="Default project created during migration recovery",
            start_date=now.date(),
            status='planning',
            client=client,
            created_at=now,
            updated_at=now
        )

def forward_null_projects(apps, schema_editor):
    FileMetadata = apps.get_model('files', 'FileMetadata')
    ProjectFolder = apps.get_model('files', 'ProjectFolder')
    ProjectAnalysis = apps.get_model('files', 'ProjectAnalysis')
    
    FileMetadata.objects.all().update(project=None)
    ProjectFolder.objects.all().update(project=None)
    ProjectAnalysis.objects.all().update(project=None)

def update_project_references(apps, schema_editor):
    FileMetadata = apps.get_model('files', 'FileMetadata')
    ProjectFolder = apps.get_model('files', 'ProjectFolder')
    ProjectAnalysis = apps.get_model('files', 'ProjectAnalysis')
    Project = apps.get_model('projects', 'Project')
    
    default_project = Project.objects.get(id=1)
    FileMetadata.objects.all().update(project=default_project)
    ProjectFolder.objects.all().update(project=default_project)
    ProjectAnalysis.objects.all().update(project=default_project)

class Migration(migrations.Migration):

    dependencies = [
        ("files", "0002_project_projectfolder_projectanalysis_filemetadata"),
        ("projects", "0001_initial"),
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectanalysis",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analyses",
                to="projects.project",
            ),
        ),
        migrations.AlterField(
            model_name="projectfolder",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="folders",
                to="projects.project",
            ),
        ),
        migrations.AlterField(
            model_name="filemetadata",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="projects.project",
            ),
        ),
        migrations.RunPython(forward_null_projects),
        migrations.RunPython(create_default_project),
        migrations.RunPython(update_project_references),
        migrations.CreateModel(
            name="ProjectMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project_path",
                    models.CharField(
                        help_text="Full path to the project directory", max_length=500
                    ),
                ),
                ("last_analyzed", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "file_structure",
                    models.JSONField(
                        blank=True,
                        help_text="JSON representation of project file structure",
                        null=True,
                    ),
                ),
                (
                    "email_summary",
                    models.TextField(
                        blank=True, help_text="Summary of processed email content"
                    ),
                ),
                (
                    "dollar_amounts",
                    models.JSONField(
                        blank=True,
                        help_text="Extracted dollar amounts from proposals",
                        null=True,
                    ),
                ),
                (
                    "scope_analysis",
                    models.JSONField(
                        blank=True, help_text="Analysis of scope of work", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metadata",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Project Metadata",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.DeleteModel(
            name="Project",
        ),
    ]
