# Generated by Django 5.2 on 2025-04-21 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0002_project_projectfolder_projectanalysis_filemetadata"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectanalysis",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analyses",
                to="projects.project",
            ),
        ),
        migrations.AlterField(
            model_name="projectfolder",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="folders",
                to="projects.project",
            ),
        ),
        migrations.AlterField(
            model_name="filemetadata",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="file_metadata",
                to="projects.project",
            ),
        ),
        migrations.CreateModel(
            name="ProjectMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project_path",
                    models.CharField(
                        help_text="Full path to the project directory", max_length=500
                    ),
                ),
                ("last_analyzed", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "file_structure",
                    models.JSONField(
                        blank=True,
                        help_text="JSON representation of project file structure",
                        null=True,
                    ),
                ),
                (
                    "email_summary",
                    models.TextField(
                        blank=True, help_text="Summary of processed email content"
                    ),
                ),
                (
                    "dollar_amounts",
                    models.JSONField(
                        blank=True,
                        help_text="Extracted dollar amounts from proposals",
                        null=True,
                    ),
                ),
                (
                    "scope_analysis",
                    models.JSONField(
                        blank=True, help_text="Analysis of scope of work", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metadata",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Project Metadata",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.DeleteModel(
            name="Project",
        ),
    ]
