# Generated by Django 5.2 on 2025-06-29 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0003_alter_projectanalysis_project_and_more"),
        ("projects", "0002_timeentry"),
    ]

    operations = [
        migrations.CreateModel(
            name="Email",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("file_type", models.CharField(max_length=50)),
                ("sender", models.CharField(max_length=255)),
                ("subject", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("date", models.DateTimeField()),
                ("attachments", models.JSONField(blank=True, null=True)),
                ("thread_id", models.CharField(max_length=255)),
                ("thread_subject", models.CharField(max_length=255)),
                ("thread_snippet", models.TextField()),
                ("thread_date", models.DateTimeField()),
                ("thread_participants", models.JSONField(blank=True, null=True)),
                ("thread_message_count", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Proposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("recipient_name", models.CharField(max_length=255)),
                ("recipient_company", models.CharField(max_length=255)),
                ("recipient_address", models.TextField()),
                (
                    "basic_services",
                    models.JSONField(
                        help_text="List of basic services and descriptions"
                    ),
                ),
                (
                    "additional_services",
                    models.JSONField(
                        blank=True,
                        help_text="List of additional services and descriptions",
                        null=True,
                    ),
                ),
                (
                    "compensation",
                    models.JSONField(help_text="Compensation details, fees, terms"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent"),
                            ("accepted", "Accepted"),
                        ],
                        default="draft",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="RoomAcousticsData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_volume", models.FloatField(blank=True, null=True)),
                ("wall_treatment_materials", models.JSONField(blank=True, null=True)),
                ("wall_treatment_volume", models.FloatField(blank=True, null=True)),
                (
                    "ceiling_treatment_materials",
                    models.JSONField(blank=True, null=True),
                ),
                ("ceiling_treatment_volume", models.FloatField(blank=True, null=True)),
                ("floor_treatment_materials", models.JSONField(blank=True, null=True)),
                ("floor_treatment_volume", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name="filemetadata",
            name="files_filem_project_b41dfc_idx",
        ),
        migrations.RemoveIndex(
            model_name="filemetadata",
            name="files_filem_file_ty_5849ff_idx",
        ),
        migrations.RemoveField(
            model_name="projectmetadata",
            name="file_structure",
        ),
        migrations.AddField(
            model_name="projectmetadata",
            name="file_structure_pretty",
            field=models.TextField(
                blank=True, help_text="Formatted file structure for display", null=True
            ),
        ),
        migrations.AlterField(
            model_name="filemetadata",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="file_metadata",
                to="projects.project",
            ),
        ),
        migrations.AlterField(
            model_name="projectanalysis",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analyses",
                to="projects.project",
            ),
        ),
        migrations.AlterField(
            model_name="projectfolder",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="folders",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="email",
            name="folder",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="emails",
                to="files.projectfolder",
            ),
        ),
        migrations.AddField(
            model_name="email",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="emails",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="proposal",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="proposals",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="roomacousticsdata",
            name="folder",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="room_acoustics_data",
                to="files.projectfolder",
            ),
        ),
        migrations.AddField(
            model_name="roomacousticsdata",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="room_acoustics_data",
                to="projects.project",
            ),
        ),
        migrations.AddIndex(
            model_name="email",
            index=models.Index(
                fields=["project", "folder"], name="files_email_project_eb582b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="roomacousticsdata",
            index=models.Index(
                fields=["project", "folder"], name="files_rooma_project_94a59d_idx"
            ),
        ),
    ]
