# Generated by Django 5.2 on 2025-04-29 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0004_update_project_references"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filemetadata",
            name="project",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="file_metadata",
                to="projects.project",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="projectanalysis",
            name="project",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analyses",
                to="projects.project",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="projectfolder",
            name="project",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="folders",
                to="projects.project",
            ),
            preserve_default=False,
        ),
    ]
