# Generated by Django 5.2 on 2025-08-07 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0004_email_proposal_roomacousticsdata_and_more"),
        ("projects", "0005_recitem_recitemattribute_recitemversion"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_path",
                    models.CharField(
                        blank=True,
                        help_text="Filesystem path if not from uploaded File",
                        max_length=1000,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Title inferred from the document",
                        max_length=255,
                    ),
                ),
                ("page_count", models.PositiveIntegerField(default=0)),
                (
                    "markdown",
                    models.TextField(
                        help_text="Markdown representation of the PDF content"
                    ),
                ),
                (
                    "summary",
                    models.TextField(help_text="Concise summary for billing context"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("processed", "Processed"), ("failed", "Failed")],
                        default="processed",
                        max_length=20,
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="document_summaries",
                        to="files.file",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_summaries",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["project", "created_at"],
                        name="files_docum_project_93e231_idx",
                    )
                ],
            },
        ),
    ]
