# Generated by Django 5.2 on 2026-01-10 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0005_documentsummary"),
        ("projects", "0007_projecttemplate_alter_project_client_activitylog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("report", "Report"),
                            ("proposal", "Proposal"),
                            ("memo", "Memo"),
                            ("letter", "Letter"),
                            ("specification", "Specification"),
                            ("drawing", "Drawing"),
                            ("calculation", "Calculation"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                (
                    "document_number",
                    models.CharField(
                        blank=True, help_text="Internal document number", max_length=50
                    ),
                ),
                (
                    "revision_number",
                    models.CharField(
                        help_text="e.g., A, B, 1, 2, or 1.0, 1.1", max_length=20
                    ),
                ),
                ("revision_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("internal_review", "Internal Review"),
                            ("client_review", "Client Review"),
                            ("approved", "Approved"),
                            ("superseded", "Superseded"),
                            ("final", "Final"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("file", models.FileField(upload_to="document_revisions/%Y/%m/")),
                (
                    "file_format",
                    models.CharField(
                        blank=True, help_text="PDF, DOCX, etc.", max_length=20
                    ),
                ),
                ("review_date", models.DateField(blank=True, null=True)),
                ("approval_date", models.DateField(blank=True, null=True)),
                ("client_approved", models.BooleanField(default=False)),
                ("client_approval_date", models.DateField(blank=True, null=True)),
                ("client_comments", models.TextField(blank=True)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of changes in this revision"
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        default=True, help_text="Is this the current/latest revision"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "prepared_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prepared_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_revisions",
                        to="projects.project",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Revision",
                "verbose_name_plural": "Document Revisions",
                "ordering": ["project", "document_number", "-revision_date"],
                "unique_together": {("project", "document_number", "revision_number")},
            },
        ),
        migrations.CreateModel(
            name="DocumentComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comment_type",
                    models.CharField(
                        choices=[
                            ("internal", "Internal Comment"),
                            ("client", "Client Comment"),
                            ("resolution", "Resolution"),
                        ],
                        default="internal",
                        max_length=20,
                    ),
                ),
                (
                    "page_reference",
                    models.CharField(
                        blank=True, help_text="Page or section reference", max_length=50
                    ),
                ),
                ("comment_text", models.TextField()),
                ("is_resolved", models.BooleanField(default=False)),
                ("resolution_text", models.TextField(blank=True)),
                ("resolved_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="document_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="files.documentrevision",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Comment",
                "verbose_name_plural": "Document Comments",
                "ordering": ["document", "created_at"],
            },
        ),
    ]
