# Generated by Django 5.2 on 2025-04-29 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0005_alter_filemetadata_project_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectmetadata",
            name="file_structure",
        ),
        migrations.AddField(
            model_name="projectmetadata",
            name="file_structure_pretty",
            field=models.TextField(
                blank=True, help_text="Formatted file structure for display", null=True
            ),
        ),
    ]
