# Generated by Django 5.2 on 2025-05-04 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0006_remove_projectmetadata_file_structure_and_more"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoomAcousticsData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_volume", models.FloatField(blank=True, null=True)),
                ("wall_treatment_materials", models.JSONField(blank=True, null=True)),
                ("wall_treatment_cost", models.FloatField(blank=True, null=True)),
                (
                    "ceiling_treatment_materials",
                    models.JSONField(blank=True, null=True),
                ),
                ("ceiling_treatment_cost", models.FloatField(blank=True, null=True)),
                ("floor_treatment_materials", models.JSONField(blank=True, null=True)),
                ("floor_treatment_cost", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name="filemetadata",
            name="files_filem_project_b41dfc_idx",
        ),
        migrations.RemoveIndex(
            model_name="filemetadata",
            name="files_filem_file_ty_5849ff_idx",
        ),
        migrations.AddField(
            model_name="roomacousticsdata",
            name="folder",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="room_acoustics_data",
                to="files.projectfolder",
            ),
        ),
        migrations.AddField(
            model_name="roomacousticsdata",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="room_acoustics_data",
                to="projects.project",
            ),
        ),
        migrations.AddIndex(
            model_name="roomacousticsdata",
            index=models.Index(
                fields=["project", "folder"], name="files_rooma_project_94a59d_idx"
            ),
        ),
    ]
