# Generated by Django 5.2 on 2026-01-11 00:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0006_documentrevision_documentcomment"),
        ("projects", "0007_projecttemplate_alter_project_client_activitylog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailScanBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "folder_paths",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of folder paths to scan for .msg files",
                    ),
                ),
                (
                    "scan_date_from",
                    models.DateField(
                        blank=True,
                        help_text="Only scan emails after this date",
                        null=True,
                    ),
                ),
                (
                    "scan_date_to",
                    models.DateField(
                        blank=True,
                        help_text="Only scan emails before this date",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("total_emails_scanned", models.IntegerField(default=0)),
                ("total_events_found", models.IntegerField(default=0)),
                ("total_milestones_created", models.IntegerField(default=0)),
                ("error_summary", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        help_text="Scan emails for a specific project",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_scan_batches",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Scan Batch",
                "verbose_name_plural": "Email Scan Batches",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectStatusIndicator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "indicator_type",
                    models.CharField(
                        choices=[
                            ("phase_start", "Phase Start"),
                            ("phase_complete", "Phase Complete"),
                            ("deliverable_sent", "Deliverable Sent"),
                            ("client_approval", "Client Approval"),
                            ("waiting_on_client", "Waiting on Client"),
                            ("active_work", "Active Work"),
                            ("on_hold", "On Hold"),
                            ("issue_flagged", "Issue Flagged"),
                        ],
                        max_length=30,
                    ),
                ),
                ("indicator_date", models.DateField()),
                ("description", models.TextField()),
                ("extracted_text", models.TextField()),
                (
                    "confidence",
                    models.CharField(
                        choices=[
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "inferred_phase",
                    models.CharField(
                        blank=True,
                        help_text="Inferred project phase name",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_indicators",
                        to="files.email",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_status_indicators",
                        to="projects.project",
                    ),
                ),
                (
                    "scan_batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indicators",
                        to="files.emailscanbatch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Status Indicator",
                "verbose_name_plural": "Project Status Indicators",
                "ordering": ["-indicator_date"],
            },
        ),
        migrations.CreateModel(
            name="EmailTimelineEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("deadline", "Deadline"),
                            ("meeting", "Meeting"),
                            ("submittal", "Submittal/Delivery"),
                            ("milestone", "Milestone"),
                            ("kickoff", "Project Kickoff"),
                            ("site_visit", "Site Visit"),
                            ("review", "Review Period"),
                            ("approval", "Approval"),
                            ("completion", "Completion"),
                            ("invoice", "Invoice/Payment"),
                            ("change_order", "Change Order"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("event_date", models.DateField()),
                ("event_description", models.CharField(max_length=500)),
                (
                    "extracted_text",
                    models.TextField(
                        help_text="The text snippet that triggered extraction"
                    ),
                ),
                (
                    "confidence",
                    models.CharField(
                        choices=[
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "extraction_method",
                    models.CharField(
                        help_text="e.g., 'regex', 'keyword', 'pattern'", max_length=50
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("confirmed", "Confirmed"),
                            ("rejected", "Rejected"),
                            ("converted", "Converted to Milestone"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeline_events",
                        to="files.email",
                    ),
                ),
                (
                    "milestone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_email_events",
                        to="projects.milestone",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_timeline_events",
                        to="projects.project",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_email_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "scan_batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="files.emailscanbatch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Timeline Event",
                "verbose_name_plural": "Email Timeline Events",
                "ordering": ["event_date", "-confidence"],
                "indexes": [
                    models.Index(
                        fields=["project", "event_date"],
                        name="files_email_project_13254a_idx",
                    ),
                    models.Index(
                        fields=["status"], name="files_email_status_72a77c_idx"
                    ),
                ],
            },
        ),
    ]
