# Generated by Django 5.2 on 2025-05-15 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0007_roomacousticsdata_and_more"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="roomacousticsdata",
            old_name="ceiling_treatment_cost",
            new_name="ceiling_treatment_volume",
        ),
        migrations.RenameField(
            model_name="roomacousticsdata",
            old_name="floor_treatment_cost",
            new_name="floor_treatment_volume",
        ),
        migrations.RenameField(
            model_name="roomacousticsdata",
            old_name="wall_treatment_cost",
            new_name="wall_treatment_volume",
        ),
        migrations.CreateModel(
            name="Proposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("recipient_name", models.CharField(max_length=255)),
                ("recipient_company", models.CharField(max_length=255)),
                ("recipient_address", models.TextField()),
                ("subject", models.CharField(max_length=255)),
                ("reference", models.CharField(blank=True, max_length=255)),
                ("introduction", models.TextField()),
                (
                    "basic_services",
                    models.JSONField(
                        help_text="List of basic services and descriptions"
                    ),
                ),
                (
                    "additional_services",
                    models.JSONField(
                        blank=True,
                        help_text="List of additional services and descriptions",
                        null=True,
                    ),
                ),
                (
                    "compensation",
                    models.JSONField(help_text="Compensation details, fees, terms"),
                ),
                ("terms", models.TextField(blank=True)),
                ("attachments", models.JSONField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent"),
                            ("accepted", "Accepted"),
                        ],
                        default="draft",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposals",
                        to="projects.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Email",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("file_type", models.CharField(max_length=50)),
                ("sender", models.CharField(max_length=255)),
                ("subject", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("date", models.DateTimeField()),
                ("attachments", models.JSONField(blank=True, null=True)),
                ("thread_id", models.CharField(max_length=255)),
                ("thread_subject", models.CharField(max_length=255)),
                ("thread_snippet", models.TextField()),
                ("thread_date", models.DateTimeField()),
                ("thread_participants", models.JSONField(blank=True, null=True)),
                ("thread_message_count", models.IntegerField()),
                (
                    "folder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emails",
                        to="files.projectfolder",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emails",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["project", "folder"],
                        name="files_email_project_eb582b_idx",
                    )
                ],
            },
        ),
    ]
