# Generated by Django 5.2 on 2025-05-22 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "files",
            "0008_rename_ceiling_treatment_cost_roomacousticsdata_ceiling_treatment_volume_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="proposal",
            name="attachments",
        ),
        migrations.RemoveField(
            model_name="proposal",
            name="introduction",
        ),
        migrations.RemoveField(
            model_name="proposal",
            name="reference",
        ),
        migrations.RemoveField(
            model_name="proposal",
            name="subject",
        ),
        migrations.RemoveField(
            model_name="proposal",
            name="terms",
        ),
    ]
