# Generated by Django 5.2.3 on 2025-07-09 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0004_email_proposal_roomacousticsdata_and_more"),
        ("projects", "0002_timeentry"),
    ]

    operations = [
        migrations.CreateModel(
            name="Milestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("due_date", models.DateField()),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("email", "Extracted from Email"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestones",
                        to="projects.project",
                    ),
                ),
                (
                    "related_email",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="milestone_links",
                        to="files.email",
                    ),
                ),
            ],
            options={
                "ordering": ["project", "due_date"],
            },
        ),
        migrations.CreateModel(
            name="ProjectPhase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("order", models.PositiveIntegerField(default=0)),
                ("percent_complete", models.FloatField(default=0)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("on_hold", "On Hold"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phases",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["project", "order"],
                "unique_together": {("project", "order")},
            },
        ),
        migrations.CreateModel(
            name="PhaseWorkLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("hours_worked", models.FloatField(default=0)),
                ("hours_invoiced", models.FloatField(default=0)),
                ("is_wip", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "phase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_logs",
                        to="projects.projectphase",
                    ),
                ),
            ],
            options={
                "ordering": ["phase", "date"],
            },
        ),
    ]
