# Generated by Django 5.2.3 on 2025-07-15 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0004_email_proposal_roomacousticsdata_and_more"),
        ("projects", "0004_scopeitem"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("sound_isolation", "Sound Isolation"),
                            (
                                "mechanical_noise_vibration",
                                "Mechanical Noise & Vibration",
                            ),
                            ("room_acoustics", "Room Acoustics"),
                            ("environmental_noise", "Environmental Noise"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent to Client"),
                            ("under_review", "Under Client Review"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("implemented", "Implemented"),
                            ("modified", "Modified"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "keywords",
                    models.TextField(
                        blank=True,
                        help_text="Keywords for email content analysis (comma-separated)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scope_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rec_items",
                        to="projects.scopeitem",
                    ),
                ),
            ],
            options={
                "ordering": ["scope_item", "category", "title"],
            },
        ),
        migrations.CreateModel(
            name="RecItemAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Attribute name, e.g., 'Insertion Loss', 'Silencer Size'",
                        max_length=100,
                    ),
                ),
                ("value", models.TextField()),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        help_text="Unit of measurement, e.g., 'dB', 'inches'",
                        max_length=20,
                    ),
                ),
                (
                    "attribute_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("number", "Number"),
                            ("boolean", "Boolean"),
                            ("file", "File Reference"),
                            ("measurement", "Measurement with Units"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rec_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributes",
                        to="projects.recitem",
                    ),
                ),
            ],
            options={
                "ordering": ["rec_item", "name"],
                "unique_together": {("rec_item", "name")},
            },
        ),
        migrations.CreateModel(
            name="RecItemVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_number", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "technical_specs",
                    models.JSONField(
                        default=dict,
                        help_text="Technical specifications as key-value pairs",
                    ),
                ),
                (
                    "change_source",
                    models.CharField(
                        choices=[
                            ("manual", "Manual Entry"),
                            ("drawing", "Drawing Update"),
                            ("email", "Email Communication"),
                            ("meeting", "Meeting Notes"),
                            ("report", "Report Update"),
                            ("client_feedback", "Client Feedback"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "change_notes",
                    models.TextField(
                        blank=True, help_text="Notes about what changed in this version"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rec_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="projects.recitem",
                    ),
                ),
                (
                    "source_email",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rec_item_versions",
                        to="files.email",
                    ),
                ),
                (
                    "source_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rec_item_versions",
                        to="files.file",
                    ),
                ),
            ],
            options={
                "ordering": ["rec_item", "version_number"],
                "unique_together": {("rec_item", "version_number")},
            },
        ),
    ]
