# Generated by Django 5.2 on 2025-11-04 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_recitem_recitemattribute_recitemversion"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProposalScanResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "proposal_file",
                    models.CharField(
                        blank=True,
                        help_text="Full path to the proposal file if found",
                        max_length=1000,
                    ),
                ),
                (
                    "raw_text",
                    models.TextField(
                        blank=True,
                        help_text="Extracted text from the proposal document",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("found", "Proposal Found"),
                            ("not_found", "No Proposal Found"),
                            ("error", "Error"),
                        ],
                        default="not_found",
                        max_length=20,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if scan failed"
                    ),
                ),
                ("scanned_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposal_scan_results",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proposal Scan Result",
                "verbose_name_plural": "Proposal Scan Results",
                "ordering": ["-scanned_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectScopeCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category_name",
                    models.CharField(
                        help_text="Scope category name (e.g., 'Emergency Generator Noise', 'STC Testing')",
                        max_length=200,
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        default=0.0,
                        help_text="Confidence score from keyword matching (0.0 to 1.0)",
                    ),
                ),
                (
                    "source_file",
                    models.CharField(
                        blank=True,
                        help_text="Source proposal file path",
                        max_length=1000,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scope_categories",
                        to="projects.project",
                    ),
                ),
                (
                    "scan_result",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="detected_categories",
                        to="projects.proposalscanresult",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Scope Category",
                "verbose_name_plural": "Project Scope Categories",
                "ordering": ["project", "-confidence_score", "category_name"],
                "unique_together": {("project", "category_name")},
            },
        ),
    ]
