# Generated by Django 5.2 on 2026-01-10 00:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0003_client_accounting_contact_email_and_more"),
        ("projects", "0006_add_proposal_scan_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "default_phases",
                    models.JSONField(
                        default=list,
                        help_text="List of phase configurations: [{'name': 'Phase Name', 'order': 1}, ...]",
                    ),
                ),
                (
                    "default_milestones",
                    models.JSONField(
                        default=list,
                        help_text="List of milestone templates: [{'name': 'Milestone', 'days_from_start': 30}, ...]",
                    ),
                ),
                (
                    "default_scope_categories",
                    models.JSONField(
                        default=list,
                        help_text="List of default scope categories for this template",
                    ),
                ),
                (
                    "estimated_duration_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Typical duration in days for this project type",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Project Template",
                "verbose_name_plural": "Project Templates",
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="project",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="projects",
                to="clients.client",
            ),
        ),
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Created"),
                            ("update", "Updated"),
                            ("delete", "Deleted"),
                            ("status_change", "Status Changed"),
                            ("file_upload", "File Uploaded"),
                            ("milestone_complete", "Milestone Completed"),
                            ("invoice_sent", "Invoice Sent"),
                            ("comment", "Comment Added"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "object_type",
                    models.CharField(
                        blank=True, help_text="Type of object affected", max_length=100
                    ),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(
                        blank=True, help_text="ID of affected object", null=True
                    ),
                ),
                (
                    "old_value",
                    models.TextField(
                        blank=True, help_text="Previous value (for updates)"
                    ),
                ),
                (
                    "new_value",
                    models.TextField(blank=True, help_text="New value (for updates)"),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Activity Log",
                "verbose_name_plural": "Activity Logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
