# Generated by Django 5.2 on 2025-08-07 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="billing_contact",
            field=models.CharField(
                blank=True, help_text="Primary billing contact person", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="billing_contact_email",
            field=models.EmailField(
                blank=True, help_text="Billing contact email address", max_length=254
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="secondary_contact",
            field=models.CharField(
                blank=True, help_text="Secondary billing contact", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="secondary_contact_email",
            field=models.EmailField(
                blank=True, help_text="Secondary contact email", max_length=254
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="special_invoice_instructions",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="client",
            name="special_negotiated_rates",
            field=models.TextField(blank=True),
        ),
    ]
