# Generated by Django 5.2 on 2025-08-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "clients",
            "0002_client_billing_contact_client_billing_contact_email_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="accounting_contact_email",
            field=models.EmailField(
                blank=True, help_text="Accounting/AP contact email", max_length=254
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="accounting_contact_name",
            field=models.CharField(
                blank=True,
                help_text="Primary accounting/AP contact name",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="invoice_format",
            field=models.CharField(
                blank=True,
                choices=[
                    ("standard_pdf", "Standard PDF via Email"),
                    ("portal_upload", "Client Portal Upload"),
                    ("edi_einvoice", "E-invoice / EDI"),
                    ("custom", "Custom Instructions"),
                ],
                help_text="Preferred invoice delivery format",
                max_length=32,
            ),
        ),
    ]
