# Generated by Django 5.2 on 2025-08-07 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
        ("files", "0004_email_proposal_roomacousticsdata_and_more"),
        ("projects", "0005_recitem_recitemattribute_recitemversion"),
    ]

    operations = [
        migrations.CreateModel(
            name="BillingEmailReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference_type",
                    models.CharField(
                        choices=[
                            ("invoice", "Invoice Email"),
                            ("payment", "Payment Email"),
                            ("proposal", "Proposal Email"),
                            ("discussion", "Billing Discussion"),
                            ("reminder", "Payment Reminder"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "billing_detail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_references",
                        to="billing.billingdetail",
                    ),
                ),
                (
                    "email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_references",
                        to="files.email",
                    ),
                ),
            ],
            options={
                "verbose_name": "Billing Email Reference",
                "verbose_name_plural": "Billing Email References",
            },
        ),
        migrations.CreateModel(
            name="ProjectInformationForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project_number",
                    models.CharField(
                        blank=True, help_text="Unique project identifier", max_length=50
                    ),
                ),
                (
                    "project_name",
                    models.CharField(
                        blank=True, help_text="Project name", max_length=200
                    ),
                ),
                (
                    "dlaa_office",
                    models.CharField(
                        blank=True,
                        help_text="DLAA Office handling the project",
                        max_length=100,
                    ),
                ),
                (
                    "project_location_city",
                    models.CharField(
                        blank=True, help_text="Project city", max_length=100
                    ),
                ),
                (
                    "project_location_state",
                    models.CharField(
                        blank=True, help_text="Project state", max_length=50
                    ),
                ),
                (
                    "originator",
                    models.CharField(
                        blank=True,
                        help_text="Person who initiated the project",
                        max_length=100,
                    ),
                ),
                (
                    "date_entered",
                    models.DateField(
                        blank=True, help_text="Date form was completed", null=True
                    ),
                ),
                (
                    "client_name",
                    models.CharField(
                        blank=True, help_text="Firm or individual name", max_length=200
                    ),
                ),
                (
                    "billing_contact",
                    models.CharField(
                        blank=True,
                        help_text="Primary billing contact person",
                        max_length=200,
                    ),
                ),
                (
                    "billing_contact_email",
                    models.EmailField(
                        blank=True,
                        help_text="Billing contact email address",
                        max_length=254,
                    ),
                ),
                (
                    "client_project_name",
                    models.CharField(
                        blank=True,
                        help_text="Client's internal project reference",
                        max_length=200,
                    ),
                ),
                (
                    "purchase_order_number",
                    models.CharField(
                        blank=True,
                        help_text="Purchase order number if applicable",
                        max_length=100,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, help_text="Contact phone number", max_length=20
                    ),
                ),
                (
                    "secondary_contact",
                    models.CharField(
                        blank=True,
                        help_text="Alternative contact person",
                        max_length=200,
                    ),
                ),
                (
                    "secondary_contact_email",
                    models.EmailField(
                        blank=True, help_text="Secondary contact email", max_length=254
                    ),
                ),
                (
                    "project_manager",
                    models.CharField(
                        blank=True, help_text="Assigned project manager", max_length=200
                    ),
                ),
                (
                    "project_start_date",
                    models.DateField(
                        blank=True, help_text="Project commencement date", null=True
                    ),
                ),
                (
                    "fee_contract_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total contract fee",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "type_of_contract",
                    models.CharField(
                        blank=True, help_text="Type of contract", max_length=100
                    ),
                ),
                (
                    "expenses",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Project expenses",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "tax_locations",
                    models.JSONField(
                        blank=True, default=list, help_text="Selected tax jurisdictions"
                    ),
                ),
                (
                    "special_negotiated_rates",
                    models.TextField(
                        blank=True, help_text="Special rates if applicable"
                    ),
                ),
                (
                    "special_invoice_instructions",
                    models.TextField(
                        blank=True, help_text="Specific invoicing instructions"
                    ),
                ),
                (
                    "retainer_received",
                    models.CharField(
                        blank=True,
                        choices=[("yes", "Yes"), ("no", "No")],
                        help_text="Whether retainer has been received",
                        max_length=3,
                    ),
                ),
                (
                    "additional_comments",
                    models.TextField(
                        blank=True, help_text="Additional notes or comments"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pif",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Information Form",
                "verbose_name_plural": "Project Information Forms",
            },
        ),
        migrations.CreateModel(
            name="BillingPhase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phase_name",
                    models.CharField(
                        choices=[
                            ("professional_services", "Professional Services"),
                            ("programming", "Programming"),
                            ("schematic_design", "Schematic Design"),
                            ("design_development", "Design Development"),
                            ("construction_documents", "Construction Documents"),
                            ("bidding_negotiation", "Bidding/Negotiation"),
                            (
                                "construction_administration",
                                "Construction Administration",
                            ),
                            ("general", "General"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "custom_phase_name",
                    models.CharField(
                        blank=True,
                        help_text="Custom phase name if 'Other' is selected",
                        max_length=100,
                    ),
                ),
                (
                    "max_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum amount for this phase",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Amount for this phase",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "subconsultant_fee_1",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="First subconsultant fee",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "subconsultant_fee_2",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Second subconsultant fee",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order of phases in the form"
                    ),
                ),
                (
                    "pif",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_phases",
                        to="billing.projectinformationform",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("pif", "phase_name", "order")},
            },
        ),
    ]
