# Generated by Django 5.2 on 2025-08-31 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_billingemailreference_projectinformationform_and_more"),
        ("projects", "0005_recitem_recitemattribute_recitemversion"),
    ]

    operations = [
        migrations.CreateModel(
            name="PIFScanBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name for this scan batch", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of what this scan covers"
                    ),
                ),
                (
                    "year_folders",
                    models.JSONField(
                        default=list, help_text="List of year folder paths to scan"
                    ),
                ),
                ("scan_date", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("total_scanned", models.IntegerField(default=0)),
                ("total_ingested", models.IntegerField(default=0)),
                ("total_skipped", models.IntegerField(default=0)),
                ("total_errors", models.IntegerField(default=0)),
                (
                    "log_file",
                    models.TextField(blank=True, help_text="Path to scan log file"),
                ),
                (
                    "error_summary",
                    models.TextField(
                        blank=True, help_text="Summary of errors encountered"
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "PIF Scan Batch",
                "verbose_name_plural": "PIF Scan Batches",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PIFScanSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name for this schedule", max_length=200
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("manual", "Manual Only"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "year_folders",
                    models.JSONField(
                        default=list, help_text="List of year folder paths to scan"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this schedule is active"
                    ),
                ),
                ("last_run", models.DateTimeField(blank=True, null=True)),
                ("next_run", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "PIF Scan Schedule",
                "verbose_name_plural": "PIF Scan Schedules",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PIFScanResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project_number",
                    models.CharField(
                        blank=True,
                        help_text="Extracted project number from path",
                        max_length=50,
                    ),
                ),
                (
                    "project_name",
                    models.CharField(
                        blank=True,
                        help_text="Extracted project name from path",
                        max_length=200,
                    ),
                ),
                (
                    "container_dir",
                    models.TextField(help_text="Full path to the container directory"),
                ),
                (
                    "folder_kind",
                    models.CharField(
                        blank=True,
                        help_text="Type of folder (Business, Documents, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "pif_file",
                    models.TextField(
                        blank=True, help_text="Full path to the PIF file if found"
                    ),
                ),
                (
                    "files_count",
                    models.IntegerField(
                        blank=True,
                        help_text="Number of files in the directory",
                        null=True,
                    ),
                ),
                (
                    "rows",
                    models.IntegerField(
                        blank=True,
                        help_text="Number of rows in the PIF file",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ingested", "Ingested"),
                            ("skipped", "Skipped"),
                            ("error", "Error"),
                        ],
                        default="skipped",
                        max_length=20,
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        help_text="Reason for status (ok, no_pif_found, error message)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pif_scan_results",
                        to="projects.project",
                    ),
                ),
                (
                    "scan_batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scan_results",
                        to="billing.pifscanbatch",
                    ),
                ),
            ],
            options={
                "verbose_name": "PIF Scan Result",
                "verbose_name_plural": "PIF Scan Results",
                "ordering": ["-created_at"],
            },
        ),
    ]
