# Generated by Django 5.2 on 2026-01-10 01:00

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0004_billingprogressnote"),
        ("clients", "0003_client_accounting_contact_email_and_more"),
        ("projects", "0007_projecttemplate_alter_project_client_activitylog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contract_number", models.CharField(max_length=50, unique=True)),
                ("title", models.CharField(max_length=200)),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("fixed_fee", "Fixed Fee"),
                            ("hourly", "Hourly/Time & Materials"),
                            ("not_to_exceed", "Not to Exceed"),
                            ("retainer", "Retainer"),
                            ("master_agreement", "Master Service Agreement"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent for Signature"),
                            ("executed", "Executed"),
                            ("amended", "Amended"),
                            ("completed", "Completed"),
                            ("terminated", "Terminated"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "contract_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "retainer_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("retainer_received", models.BooleanField(default=False)),
                ("effective_date", models.DateField()),
                ("expiration_date", models.DateField(blank=True, null=True)),
                (
                    "execution_date",
                    models.DateField(
                        blank=True, help_text="Date contract was signed", null=True
                    ),
                ),
                (
                    "contract_file",
                    models.FileField(blank=True, null=True, upload_to="contracts/"),
                ),
                (
                    "scope_summary",
                    models.TextField(
                        blank=True, help_text="Brief summary of contracted scope"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contracts",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contract",
                "verbose_name_plural": "Contracts",
                "ordering": ["-effective_date"],
            },
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("travel", "Travel"),
                            ("lodging", "Lodging"),
                            ("meals", "Meals"),
                            ("equipment_rental", "Equipment Rental"),
                            ("materials", "Materials"),
                            ("shipping", "Shipping/Courier"),
                            ("printing", "Printing/Reproduction"),
                            ("software", "Software"),
                            ("subconsultant", "Subconsultant"),
                            ("permits", "Permits/Fees"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.CharField(max_length=500)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "is_billable",
                    models.BooleanField(
                        default=True, help_text="Can be billed to client"
                    ),
                ),
                (
                    "markup_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Markup percentage when billing to client",
                        max_digits=5,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("invoiced", "Invoiced to Client"),
                            ("paid", "Paid"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("expense_date", models.DateField()),
                ("vendor", models.CharField(blank=True, max_length=200)),
                (
                    "receipt",
                    models.FileField(
                        blank=True, null=True, upload_to="expense_receipts/"
                    ),
                ),
                ("approved_date", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_expenses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expenses",
                        to="billing.billingdetail",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to="projects.project",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_expenses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Expense",
                "verbose_name_plural": "Expenses",
                "ordering": ["-expense_date"],
            },
        ),
        migrations.CreateModel(
            name="Retainer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "initial_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "current_balance",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("received_date", models.DateField()),
                ("expiration_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retainers",
                        to="clients.client",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retainers",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Retainer",
                "verbose_name_plural": "Retainers",
                "ordering": ["-received_date"],
            },
        ),
        migrations.CreateModel(
            name="RetainerTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("deposit", "Deposit"),
                            ("drawdown", "Drawdown"),
                            ("refund", "Refund"),
                            ("adjustment", "Adjustment"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("description", models.CharField(max_length=500)),
                ("transaction_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="billing.billingdetail",
                    ),
                ),
                (
                    "retainer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="billing.retainer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Retainer Transaction",
                "verbose_name_plural": "Retainer Transactions",
                "ordering": ["-transaction_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContractAmendment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amendment_number", models.CharField(max_length=20)),
                (
                    "amendment_type",
                    models.CharField(
                        choices=[
                            ("scope_change", "Scope Change"),
                            ("fee_increase", "Fee Increase"),
                            ("fee_decrease", "Fee Decrease"),
                            ("time_extension", "Time Extension"),
                            ("terms_change", "Terms Change"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "amount_change",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Positive for increase, negative for decrease",
                        max_digits=12,
                    ),
                ),
                (
                    "new_total",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="New total contract amount after amendment",
                        max_digits=12,
                    ),
                ),
                ("effective_date", models.DateField()),
                ("execution_date", models.DateField(blank=True, null=True)),
                (
                    "amendment_file",
                    models.FileField(
                        blank=True, null=True, upload_to="contract_amendments/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="amendments",
                        to="billing.contract",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contract Amendment",
                "verbose_name_plural": "Contract Amendments",
                "ordering": ["contract", "amendment_number"],
                "unique_together": {("contract", "amendment_number")},
            },
        ),
    ]
