# Generated by Django 5.2 on 2026-01-10 01:00

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0007_projecttemplate_alter_project_client_activitylog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Office",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "code",
                    models.CharField(
                        help_text="Short code (e.g., 'HNL', 'LA')",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("address", models.TextField(blank=True)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=50)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Office",
                "verbose_name_plural": "Offices",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Subconsultant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=200)),
                ("contact_name", models.CharField(max_length=200)),
                ("contact_email", models.EmailField(max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                ("address", models.TextField(blank=True)),
                (
                    "specialty",
                    models.CharField(
                        blank=True, help_text="Area of expertise", max_length=200
                    ),
                ),
                (
                    "services",
                    models.JSONField(
                        blank=True, default=list, help_text="List of services provided"
                    ),
                ),
                ("w9_on_file", models.BooleanField(default=False)),
                ("insurance_on_file", models.BooleanField(default=False)),
                ("insurance_expiration", models.DateField(blank=True, null=True)),
                (
                    "standard_hourly_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_preferred",
                    models.BooleanField(
                        default=False, help_text="Preferred vendor status"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Subconsultant",
                "verbose_name_plural": "Subconsultants",
                "ordering": ["company_name"],
            },
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("sound_level_meter", "Sound Level Meter"),
                            ("analyzer", "Acoustic Analyzer"),
                            ("microphone", "Microphone"),
                            ("calibrator", "Calibrator"),
                            ("vibration", "Vibration Equipment"),
                            ("software", "Software License"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("manufacturer", models.CharField(blank=True, max_length=100)),
                ("model_number", models.CharField(blank=True, max_length=100)),
                ("serial_number", models.CharField(max_length=100, unique=True)),
                (
                    "asset_tag",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("in_use", "In Use"),
                            ("maintenance", "Under Maintenance"),
                            ("calibration", "Out for Calibration"),
                            ("retired", "Retired"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                ("last_calibration_date", models.DateField(blank=True, null=True)),
                ("calibration_due_date", models.DateField(blank=True, null=True)),
                (
                    "calibration_interval_days",
                    models.PositiveIntegerField(
                        default=365, help_text="Days between calibrations"
                    ),
                ),
                (
                    "calibration_certificate",
                    models.FileField(
                        blank=True, null=True, upload_to="calibration_certs/"
                    ),
                ),
                ("purchase_date", models.DateField(blank=True, null=True)),
                (
                    "purchase_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "replacement_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "specifications",
                    models.JSONField(
                        blank=True, default=dict, help_text="Technical specifications"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "office",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="equipment",
                        to="resources.office",
                    ),
                ),
            ],
            options={
                "verbose_name": "Equipment",
                "verbose_name_plural": "Equipment",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="StaffMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Administrator"),
                            ("principal", "Principal"),
                            ("project_manager", "Project Manager"),
                            ("senior_engineer", "Senior Engineer"),
                            ("engineer", "Engineer"),
                            ("junior_engineer", "Junior Engineer"),
                            ("technician", "Technician"),
                            ("intern", "Intern"),
                            ("accounting", "Accounting"),
                            ("administrative", "Administrative"),
                        ],
                        default="engineer",
                        max_length=30,
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, help_text="Job title", max_length=100),
                ),
                (
                    "employment_status",
                    models.CharField(
                        choices=[
                            ("full_time", "Full Time"),
                            ("part_time", "Part Time"),
                            ("contractor", "Contractor"),
                            ("inactive", "Inactive"),
                        ],
                        default="full_time",
                        max_length=20,
                    ),
                ),
                (
                    "standard_hourly_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Standard billing rate per hour",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "internal_cost_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Internal cost rate for budget calculations",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "overtime_multiplier",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.5"),
                        help_text="Multiplier for overtime hours",
                        max_digits=3,
                    ),
                ),
                (
                    "weekly_capacity_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("40.0"),
                        help_text="Available hours per week",
                        max_digits=5,
                    ),
                ),
                (
                    "skills",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of skills/specializations",
                    ),
                ),
                (
                    "certifications",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Professional certifications",
                    ),
                ),
                ("phone_extension", models.CharField(blank=True, max_length=10)),
                ("mobile_phone", models.CharField(blank=True, max_length=20)),
                ("emergency_contact", models.CharField(blank=True, max_length=200)),
                ("hire_date", models.DateField(blank=True, null=True)),
                ("termination_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "office",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff",
                        to="resources.office",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Staff Member",
                "verbose_name_plural": "Staff Members",
                "ordering": ["user__last_name", "user__first_name"],
            },
        ),
        migrations.CreateModel(
            name="EquipmentUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("checkout_date", models.DateTimeField()),
                ("return_date", models.DateTimeField(blank=True, null=True)),
                ("purpose", models.CharField(blank=True, max_length=200)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_records",
                        to="resources.equipment",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment_usage",
                        to="projects.project",
                    ),
                ),
                (
                    "checked_out_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="equipment_checkouts",
                        to="resources.staffmember",
                    ),
                ),
            ],
            options={
                "verbose_name": "Equipment Usage",
                "verbose_name_plural": "Equipment Usage Records",
                "ordering": ["-checkout_date"],
            },
        ),
        migrations.CreateModel(
            name="SubconsultantContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contract_number", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
                ("scope_of_work", models.TextField(blank=True)),
                (
                    "contract_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "amount_invoiced",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending Approval"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "contract_file",
                    models.FileField(
                        blank=True, null=True, upload_to="subconsultant_contracts/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subconsultant_contracts",
                        to="projects.project",
                    ),
                ),
                (
                    "subconsultant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contracts",
                        to="resources.subconsultant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subconsultant Contract",
                "verbose_name_plural": "Subconsultant Contracts",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="ProjectAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("lead", "Project Lead"),
                            ("manager", "Project Manager"),
                            ("engineer", "Engineer"),
                            ("reviewer", "Reviewer"),
                            ("support", "Support"),
                        ],
                        default="engineer",
                        max_length=20,
                    ),
                ),
                (
                    "allocation_percent",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="Percentage of time allocated to this project",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "hourly_rate_override",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Override the staff member's standard rate for this project",
                        max_digits=8,
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="projects.project",
                    ),
                ),
                (
                    "staff_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="resources.staffmember",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Assignment",
                "verbose_name_plural": "Project Assignments",
                "ordering": ["-is_active", "project", "staff_member"],
                "unique_together": {("project", "staff_member")},
            },
        ),
    ]
